"""The tier 2 FastAPI application.

Kept separate from ``inventory_engine.api.app`` (tier 1) rather than bolted onto it. Tier 1
serves precomputed M5 results out of a read-only DuckDB file and has no reason to acquire a
Postgres dependency, a Redis dependency, or an upload surface. They are mounted together by
:func:`create_app` when both are wanted, and each still runs alone.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from typing import Final

from fastapi import FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from inventory_engine.service.observability import (
    EVENT_PAGE_VIEW,
    analytics,
    bind_request_id,
    configure_logging,
    init_sentry,
    visitor_id,
)
from inventory_engine.service.routers import full_forecast
from inventory_engine.service.settings import get_settings

log = logging.getLogger(__name__)

#: Header carrying the id that joins an API log line to the worker log line it caused.
REQUEST_ID_HEADER = "X-Request-ID"

#: Anonymous per-browser id, so PostHog can count users and active users without accounts.
#: Generated by the dashboard into localStorage; it identifies a browser, not a person, and
#: nothing links it to a name, an email or a company.
CLIENT_ID_HEADER = "X-Client-ID"


def create_app(*, enable_cors: bool = True, configure_observability: bool = True) -> FastAPI:
    """Build the tier 2 app.

    Args:
        enable_cors: Allow browser calls from another origin. The dashboard is a static
            file the user may open from disk (``file://``, which sends ``Origin: null``)
            or from a different host than the API, so the Full-forecast tab cannot reach
            this service without it.
        configure_observability: Install JSON logging and Sentry. Off in tests, which want
            pytest's own log capture and must never reach a real DSN.

    """
    if configure_observability:
        configure_logging("api")
        init_sentry("api")

    app = FastAPI(
        title="Inventory Optimization Engine — Full Forecast",
        description=(
            "Upload your own sales history, get a backtested per-SKU quantile forecast and "
            "an order recommendation. Refuses data that cannot support one, and says why."
        ),
        version=full_forecast.VERSION,
    )

    if enable_cors:
        # allow_origins=["*"] is correct *because* there is no auth and no cookie: there is
        # no ambient authority for a cross-site request to abuse. This must be revisited in
        # the same change that introduces accounts, not after it.
        app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],
            allow_credentials=False,
            # DELETE is here because /datasets/{id} exists. It was missed when that endpoint
            # was added, which meant the API offered a way to delete your data and the
            # browser was forbidden from calling it -- the preflight returned "GET, POST".
            # Listed explicitly rather than "*" so adding a method stays a deliberate act.
            allow_methods=["GET", "POST", "DELETE"],
            allow_headers=["*"],
            expose_headers=[REQUEST_ID_HEADER, CLIENT_ID_HEADER],
        )

    app.middleware("http")(_request_id_middleware)
    app.include_router(full_forecast.router)
    _mount_dashboard(app)
    return app


def _mount_dashboard(app: FastAPI) -> None:
    """Serve the built dashboard at ``/``, if one is configured and actually present.

    Why the service hosts its own page
    ----------------------------------
    The Full forecast tab fetches this API from the browser. Hosted anywhere else that is a
    cross-origin request, and a published Artifact page cannot make one at all -- its
    runtime blocks every external host, with no capability to opt out. Serving the page from
    the same origin as the API removes the problem instead of working around it.

    **Mounted last, on purpose.** Starlette matches routes in registration order, so every
    endpoint is already claimed by the time this catch-all is added. Without that ordering a
    file called ``dashboard/health`` would be served in place of the health check, and the
    API would look like it had vanished. ``tests/test_service_upload`` pins it.

    A configured directory that does not exist is treated as "no page", not as a fatal
    error: ``StaticFiles`` raises at construction, which would take the entire API down over
    a missing static file. That is the same failure shape as resolving the festival demand
    table from a repository root that does not exist once the package is installed -- once
    was enough.
    """
    configured = get_settings().dashboard_dir
    if configured is None or not configured.is_dir():
        return
    app.mount("/", StaticFiles(directory=configured, html=True), name="dashboard")


async def _request_id_middleware(request: Request, call_next: Callable) -> Response:
    """Attach a request id to the request, the log context and the response.

    Honours an inbound ``X-Request-ID`` so a caller that already has a trace id keeps it,
    and generates one otherwise. Binding it into the contextvar here is what makes every
    log line inside the handler joinable without any call site having to remember to pass
    it; the same id is written onto the job row, so the worker's lines join too.
    """
    request_id = bind_request_id(request.headers.get(REQUEST_ID_HEADER))
    request.state.request_id = request_id
    request.state.client_id = request.headers.get(CLIENT_ID_HEADER) or "anonymous"
    response = await call_next(request)
    response.headers[REQUEST_ID_HEADER] = request_id
    _count_page_view(request, response)
    return response


#: Paths that mean "somebody opened the dashboard". The mount serves the page at both,
#: depending on whether the browser followed the directory index.
_PAGE_PATHS: Final = frozenset({"/", "/index.html"})


def _count_page_view(request: Request, response: Response) -> None:
    """Record one dashboard page load, if that is what this request was.

    Server-side on purpose. Every other event this service records fires only once
    somebody uploads a file, so the funnel could show four people while the site had four
    thousand readers -- and the calculator, which is the part most visitors actually use,
    would be invisible either way. Counting here needs no cookie, no client script and no
    third party in the browser: the page stays exactly as self-contained as it claims.

    The identifier is a day-scoped hash of address and user agent, computed and discarded
    inside :func:`visitor_id`. Never raises -- a counting failure must not turn into a
    failed page load.
    """
    if request.method != "GET" or request.url.path not in _PAGE_PATHS:
        return
    if response.status_code >= 400:
        return
    try:
        client = request.client
        analytics().capture(
            EVENT_PAGE_VIEW,
            visitor_id(client.host if client else None, request.headers.get("user-agent")),
            path=request.url.path,
        )
    except Exception:  # noqa: BLE001 - analytics must never break a page load
        log.debug("page view not counted", exc_info=True)


app = create_app()
