"""The tier 2 FastAPI application.

Kept separate from ``inventory_engine.api.app`` (tier 1) rather than bolted onto it. Tier 1
serves precomputed M5 results out of a read-only DuckDB file and has no reason to acquire a
Postgres dependency, a Redis dependency, or an upload surface. They are mounted together by
:func:`create_app` when both are wanted, and each still runs alone.
"""

from __future__ import annotations

from collections.abc import Callable

from fastapi import FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware

from inventory_engine.service.observability import (
    bind_request_id,
    configure_logging,
    init_sentry,
)
from inventory_engine.service.routers import full_forecast

#: Header carrying the id that joins an API log line to the worker log line it caused.
REQUEST_ID_HEADER = "X-Request-ID"

#: Anonymous per-browser id, so PostHog can count users and active users without accounts.
#: Generated by the dashboard into localStorage; it identifies a browser, not a person, and
#: nothing links it to a name, an email or a company.
CLIENT_ID_HEADER = "X-Client-ID"


def create_app(*, enable_cors: bool = True, configure_observability: bool = True) -> FastAPI:
    """Build the tier 2 app.

    Args:
        enable_cors: Allow browser calls from another origin. The dashboard is a static
            file the user may open from disk (``file://``, which sends ``Origin: null``)
            or from a different host than the API, so the Full-forecast tab cannot reach
            this service without it.
        configure_observability: Install JSON logging and Sentry. Off in tests, which want
            pytest's own log capture and must never reach a real DSN.

    """
    if configure_observability:
        configure_logging("api")
        init_sentry("api")

    app = FastAPI(
        title="Inventory Optimization Engine — Full Forecast",
        description=(
            "Upload your own sales history, get a backtested per-SKU quantile forecast and "
            "an order recommendation. Refuses data that cannot support one, and says why."
        ),
        version=full_forecast.VERSION,
    )

    if enable_cors:
        # allow_origins=["*"] is correct *because* there is no auth and no cookie: there is
        # no ambient authority for a cross-site request to abuse. This must be revisited in
        # the same change that introduces accounts, not after it.
        app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],
            allow_credentials=False,
            allow_methods=["GET", "POST"],
            allow_headers=["*"],
            expose_headers=[REQUEST_ID_HEADER, CLIENT_ID_HEADER],
        )

    app.middleware("http")(_request_id_middleware)
    app.include_router(full_forecast.router)
    return app


async def _request_id_middleware(request: Request, call_next: Callable) -> Response:
    """Attach a request id to the request, the log context and the response.

    Honours an inbound ``X-Request-ID`` so a caller that already has a trace id keeps it,
    and generates one otherwise. Binding it into the contextvar here is what makes every
    log line inside the handler joinable without any call site having to remember to pass
    it; the same id is written onto the job row, so the worker's lines join too.
    """
    request_id = bind_request_id(request.headers.get(REQUEST_ID_HEADER))
    request.state.request_id = request_id
    request.state.client_id = request.headers.get(CLIENT_ID_HEADER) or "anonymous"
    response = await call_next(request)
    response.headers[REQUEST_ID_HEADER] = request_id
    return response


app = create_app()
