"""Initial tier 2 schema: datasets, dataset_skus, forecast_jobs, forecast_results.

Hand-written rather than autogenerated, for one specific reason: the models declare their
JSON columns as ``JSON().with_variant(JSONB(), "postgresql")`` so the endpoint tests can run
on SQLite, and ``alembic revision --autogenerate`` renders that as plain ``sa.JSON()`` --
dropping the variant and creating ``json`` columns on Postgres instead of ``jsonb``. The
difference is not cosmetic: ``json`` stores the source text and cannot be indexed with GIN,
so a later "which datasets excluded this SKU" query would have no index available.

Migrations only ever run against Postgres (tests use ``Base.metadata.create_all``), so the
types here are the Postgres ones, stated outright.

Revision ID: 0001_initial_schema
Revises:
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None

JOB_STATUS = sa.Enum("queued", "running", "done", "failed", name="job_status")


def upgrade() -> None:
    """Create the tier 2 tables."""
    op.create_table(
        "datasets",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("original_filename", sa.String(512)),
        sa.Column("storage_uri", sa.String(1024), nullable=False),
        sa.Column("sha256", sa.String(64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("rows_read", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("sku_count_admitted", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("sku_count_rejected", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("first_date", sa.Date()),
        sa.Column("last_date", sa.Date()),
        sa.Column("column_mapping", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("warnings", postgresql.JSONB(), nullable=False, server_default="[]"),
    )
    op.create_index("ix_datasets_sha256", "datasets", ["sha256"])

    op.create_table(
        "dataset_skus",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("dataset_id", sa.Uuid(), sa.ForeignKey("datasets.id", ondelete="CASCADE"), nullable=False),
        sa.Column("sku", sa.String(256), nullable=False),
        sa.Column("admitted", sa.Boolean(), nullable=False),
        sa.Column("n_days", sa.Integer(), nullable=False),
        sa.Column("n_obs", sa.Integer(), nullable=False),
        sa.Column("n_nonnull", sa.Integer(), nullable=False),
        sa.Column("max_gap_days", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("first_date", sa.Date()),
        sa.Column("last_date", sa.Date()),
        sa.Column("reasons", postgresql.JSONB(), nullable=False, server_default="[]"),
    )
    op.create_index("ix_dataset_skus_dataset_id", "dataset_skus", ["dataset_id"])
    # One row per (dataset, sku). The gate groups by SKU, so a duplicate here would mean a
    # bug upstream rather than legitimate data -- catch it at write time.
    op.create_unique_constraint("uq_dataset_skus_dataset_sku", "dataset_skus", ["dataset_id", "sku"])

    op.create_table(
        "forecast_jobs",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("dataset_id", sa.Uuid(), sa.ForeignKey("datasets.id", ondelete="CASCADE"), nullable=False),
        sa.Column("status", JOB_STATUS, nullable=False, server_default="queued"),
        sa.Column("horizon", sa.Integer(), nullable=False),
        sa.Column("margin_rate", sa.Float(), nullable=False),
        sa.Column("spoilage_rate", sa.Float(), nullable=False),
        sa.Column("holding_rate", sa.Float(), nullable=False),
        sa.Column("request_id", sa.String(64), nullable=False),
        sa.Column("enqueued_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("error", sa.Text()),
    )
    op.create_index("ix_forecast_jobs_dataset_id", "forecast_jobs", ["dataset_id"])
    op.create_index("ix_forecast_jobs_status", "forecast_jobs", ["status"])
    op.create_index("ix_forecast_jobs_request_id", "forecast_jobs", ["request_id"])

    op.create_table(
        "forecast_results",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("job_id", sa.Uuid(), sa.ForeignKey("forecast_jobs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("sku", sa.String(256), nullable=False),
        sa.Column("method_used", sa.String(64), nullable=False),
        sa.Column("method_reason", sa.Text(), nullable=False),
        sa.Column("n_folds", sa.Integer(), nullable=False),
        sa.Column("mase_model", sa.Float()),
        sa.Column("mase_model_spread", sa.Float()),
        sa.Column("mase_baseline", sa.Float()),
        sa.Column("mase_baseline_spread", sa.Float()),
        sa.Column("pinball_model", sa.Float()),
        sa.Column("pinball_baseline", sa.Float()),
        sa.Column("critical_ratio", sa.Float(), nullable=False),
        sa.Column("order_qty", sa.Float(), nullable=False),
        sa.Column("expected_cost", sa.Float()),
        sa.Column("unit_price", sa.Float()),
        sa.Column("price_is_fallback", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("series", postgresql.JSONB(), nullable=False, server_default="{}"),
    )
    op.create_index("ix_forecast_results_job_id", "forecast_results", ["job_id"])
    op.create_unique_constraint("uq_forecast_results_job_sku", "forecast_results", ["job_id", "sku"])


def downgrade() -> None:
    """Drop the tier 2 tables and the enum type they share."""
    op.drop_table("forecast_results")
    op.drop_table("forecast_jobs")
    op.drop_table("dataset_skus")
    op.drop_table("datasets")
    # Dropped explicitly: Postgres keeps an enum type after the last table using it goes,
    # so a re-run of upgrade() would fail with "type job_status already exists".
    JOB_STATUS.drop(op.get_bind(), checkfirst=True)
